spring:
  cloud:
    gateway:
      routes:
        - id: ProductService
          uri: lb://ProductService
#          uri: http://localhost:9001
          predicates:
#            - Path= /api/**
            - Path=/product/v3/api-docs,/api/** # add a route for Swagger api-docs
          filters:
            - AuthenticationFilter



springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /product/v3/api-docs
        name: Product Service


##        - id: restaurant-service
##          uri: lb://RESTAURANT-SERVICE
##          predicates:
##            - Path=/restaurant/**
##          filters:
##            - AuthenticationFilter
#
#
#spring:
#  application:
#    name: ProductService
