spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://ProductService
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter
##        - id: restaurant-service
##          uri: lb://RESTAURANT-SERVICE
##          predicates:
##            - Path=/restaurant/**
##          filters:
##            - AuthenticationFilter
#
#
#spring:
#  application:
#    name: ProductService
